

vlog "E:/F/FPGAcode/SDR-radio-receiver/DE0-nano/SDRrceeiver/mfir_sim/altera_avalon_sc_fifo.v"                        
vcom "E:/F/FPGAcode/SDR-radio-receiver/DE0-nano/SDRrceeiver/mfir_sim/auk_dspip_math_pkg_hpfir.vhd"                   
vcom "E:/F/FPGAcode/SDR-radio-receiver/DE0-nano/SDRrceeiver/mfir_sim/auk_dspip_lib_pkg_hpfir.vhd"                    
vcom "E:/F/FPGAcode/SDR-radio-receiver/DE0-nano/SDRrceeiver/mfir_sim/auk_dspip_avalon_streaming_controller_hpfir.vhd"
vcom "E:/F/FPGAcode/SDR-radio-receiver/DE0-nano/SDRrceeiver/mfir_sim/auk_dspip_avalon_streaming_sink_hpfir.vhd"      
vcom "E:/F/FPGAcode/SDR-radio-receiver/DE0-nano/SDRrceeiver/mfir_sim/auk_dspip_avalon_streaming_source_hpfir.vhd"    
vcom "E:/F/FPGAcode/SDR-radio-receiver/DE0-nano/SDRrceeiver/mfir_sim/auk_dspip_roundsat_hpfir.vhd"                   
vcom "E:/F/FPGAcode/SDR-radio-receiver/DE0-nano/SDRrceeiver/mfir_sim/dspba_library_package.vhd"                      
vcom "E:/F/FPGAcode/SDR-radio-receiver/DE0-nano/SDRrceeiver/mfir_sim/dspba_library.vhd"                              
vcom "E:/F/FPGAcode/SDR-radio-receiver/DE0-nano/SDRrceeiver/mfir_sim/mfir_rtl.vhd"                                   
vcom "E:/F/FPGAcode/SDR-radio-receiver/DE0-nano/SDRrceeiver/mfir_sim/mfir_ast.vhd"                                   
vcom "E:/F/FPGAcode/SDR-radio-receiver/DE0-nano/SDRrceeiver/mfir_sim/mfir.vhd"                                       
vcom "E:/F/FPGAcode/SDR-radio-receiver/DE0-nano/SDRrceeiver/mfir_sim/mfir_tb.vhd"                                    
