

ncvlog      "E:/F/FPGAcode/SDR-radio-receiver/DE0-nano/SDRrceeiver/mfir_sim/altera_avalon_sc_fifo.v"                        
ncvhdl -v93 "E:/F/FPGAcode/SDR-radio-receiver/DE0-nano/SDRrceeiver/mfir_sim/auk_dspip_math_pkg_hpfir.vhd"                   
ncvhdl -v93 "E:/F/FPGAcode/SDR-radio-receiver/DE0-nano/SDRrceeiver/mfir_sim/auk_dspip_lib_pkg_hpfir.vhd"                    
ncvhdl -v93 "E:/F/FPGAcode/SDR-radio-receiver/DE0-nano/SDRrceeiver/mfir_sim/auk_dspip_avalon_streaming_controller_hpfir.vhd"
ncvhdl -v93 "E:/F/FPGAcode/SDR-radio-receiver/DE0-nano/SDRrceeiver/mfir_sim/auk_dspip_avalon_streaming_sink_hpfir.vhd"      
ncvhdl -v93 "E:/F/FPGAcode/SDR-radio-receiver/DE0-nano/SDRrceeiver/mfir_sim/auk_dspip_avalon_streaming_source_hpfir.vhd"    
ncvhdl -v93 "E:/F/FPGAcode/SDR-radio-receiver/DE0-nano/SDRrceeiver/mfir_sim/auk_dspip_roundsat_hpfir.vhd"                   
ncvhdl -v93 "E:/F/FPGAcode/SDR-radio-receiver/DE0-nano/SDRrceeiver/mfir_sim/dspba_library_package.vhd"                      
ncvhdl -v93 "E:/F/FPGAcode/SDR-radio-receiver/DE0-nano/SDRrceeiver/mfir_sim/dspba_library.vhd"                              
ncvhdl -v93 "E:/F/FPGAcode/SDR-radio-receiver/DE0-nano/SDRrceeiver/mfir_sim/mfir_rtl.vhd"                                   
ncvhdl -v93 "E:/F/FPGAcode/SDR-radio-receiver/DE0-nano/SDRrceeiver/mfir_sim/mfir_ast.vhd"                                   
ncvhdl -v93 "E:/F/FPGAcode/SDR-radio-receiver/DE0-nano/SDRrceeiver/mfir_sim/mfir.vhd"                                       
ncvhdl -v93 "E:/F/FPGAcode/SDR-radio-receiver/DE0-nano/SDRrceeiver/mfir_sim/mfir_tb.vhd"                                    
